sudo: false
language: cpp
compiler: gcc
before_script:
  - export COVERALLS_SERVICE_NAME=travis-ci
  - wget https://googlemock.googlecode.com/files/gmock-1.6.0.zip -O /tmp/gmock.zip
  - cd /tmp && unzip /tmp/gmock.zip
  - cd /tmp/gmock-1.6.0 && mkdir build && cd build && cmake .. && make -j4 && cd ../gtest && mkdir build && cd build && cmake .. && make -j4
  - export GMOCK_HOME=/tmp/gmock-1.6.0
  - cd ~/build/qiubix/Daredevil
  - mkdir build && cd build
script: cmake .. -DCMAKE_BUILD_TYPE=Debug && make && make coveralls
