sudo: false
language: cpp
compiler: gcc
before_script:
  - wget https://googlemock.googlecode.com/files/gmock-1.7.0.zip -O /tmp/gmock.zip
  - cd /tmp && unzip /tmp/gmock.zip
  - cd /tmp/gmock-1.7.0 && cmake . && make && cd gtest && cmake . && make
  - export GMOCK_ROOT=/tmp/gmock-1.7.0
script: cmake . && make && make test
